import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import UserDashBoard from './DashBoardLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function DashBoardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserDashBoard>

                    {children}
                </UserDashBoard>
            </body>
        </html>
    )
}
